### ISSUE TITLE
Problems retrieving information

### ISSUE THREAD

**Issue by jordiporcel** [maros/Zway-WeatherUnderground#2]
Hello.

First, congratulations on the great work

And I think I have a problem in data recovery.

http://api.wunderground.com/api/REDACTED/geolookup/conditions/forecast/q/zmw:00000.14.08181.json

You should retrieve more information?
Humidity....

![weather3](https://cloud.githubusercontent.com/assets/17791530/13743632/3245daa8-e9e3-11e5-8743-15270c721283.JPG)
![weather2](https://cloud.githubusercontent.com/assets/17791530/13743633/3245f998-e9e3-11e5-98a3-465c3cf11d5a.JPG)

I'm new to this whole world
Very Thanks.

**Comment by maros** [comment]
Please don't publish your API key - this is meant to stay private (i have removed it from your ticket - but it is still visible in the screenshot)

Location should not be the full api request URL, but only 
country/city (eg. "Australia/Sydney")
latitude,longitude (eg. "37.8,-122.4")
airport code (eg. "KJFK")
pws:PWSID (eg. "pws:KCASANFR70")
autoip

**Comment by jordiporcel** [comment]
Heelo.

Ok.

Thanks
