### ISSUE TITLE
wrong URL?

### ISSUE THREAD

**Issue by michapr** [maros/Zway-WeatherUnderground#6]
It looks like there is a wrong URL inside.

I get the error
[2021-11-27 17:34:40.231] [I] [core] {"status":503,"statusText":"Service Unavailable","url":"http://api.wunderground.com/api/[my_key]/conditions/forecast/astronomy/q/52.368790,13.633740.json",

but should be (as far as I understand) like
https://api.weather.com/v3/wx/forecast/daily/5day?geocode=52.368790,13.633740&format=json&units=m&language=en-US&apiKey=[my_key]

API is open again for free if you create a personal weather station there (it maybe a Raspberry ;)...) - then you can get API key.

Can you check it please? I hope that data format was not changed....

Thanks!
Michael

**Comment by sieberma-de** [comment]
Hi there,

I'm facing the exact same issue. For this reason the module is non-functional.

If I'm not mistaken the original wunderground API is out of service and got replaced by the Weather Company's API (api.weather.com).
Wondering if you @michapr could update the module to make it work again?

Thanks in advance!

cheers Markus

**Comment by michapr** [comment]
Sorry, I do not use this module more.
But you can edit the code yourself in installed file index.js in line 241. it was then working for me.

**Comment by sieberma-de** [comment]
Hi Michael, thanks for your prompt reply!
I'll have a look accordingly.
However, I'm wondering if the module should be still available in Z-wave.me app store if not working anymore.
